# Starter pipeline
trigger:
  - main

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.15.1'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'TestAppConnectionName'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform init
      terraform plan
      terraform apply
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
